Add Connect to EC2 and Deploy CLIENT&API

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -12,22 +12,35 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3    
         
-      # Step 2: Check if Docker Image Exists
-      - name: Check if Docker Image Exists
-        id: check_image
+      # Step 2: Check if Docker Image Exists for API
+      - name: Check if Docker Image Exists API
+        id: check_image_API
         run: |
-          REPOSITORY="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_NAME" }}  
+          REPOSITORYAPI="${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-api"  
           TAG="latest"
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}/)
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/${REPOSITORYAPI}/tags/${TAG}/)
           if [ "$RESPONSE" -ne 200 ]; then
               echo "Docker image not found. Exiting workflow."
               exit 1
           fi
           echo "Docker image exists. Proceeding to deployment."
 
-      # Step 3: Set AWS Credentials in Environment Variables
+      # Step 3: Check if Docker Image Exists for Client
+      - name: Check if Docker Image Exists Client
+        id: check_image_client
+        run: |
+          REPOSITORYCLIENT="${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-client"
+          TAG="latest"
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/${REPOSITORYCLIENT}/tags/${TAG}/)
+          if [ "$RESPONSE" -ne 200 ]; then
+              echo "Docker image not found. Exiting workflow."
+              exit 1
+          fi
+          echo "Docker image exists. Proceeding to deployment."
+
+      # Step 4: Set AWS Credentials in Environment Variables
       - name: Set AWS Credentials
-        if: ${{ steps.check_image.outcome == 'success' }}
+        if: ${{ steps.check_image_API.outcome == 'success' && steps.check_image_client.outcome == 'success' }}
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -35,7 +48,7 @@ jobs:
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: echo "AWS credentials set."
 
-      # Step 4: Create EC2 Instance and Deploy the Application
+     # Step 5: Create EC2 Instance and Deploy the Application
       - name: Create EC2 Instance and Deploy the Application
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -43,7 +56,6 @@ jobs:
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
-          # Define instance details
           INSTANCE_ID=$(aws ec2 run-instances \
             --image-id ami-06b21ccaeff8cd686 \
             --instance-type t2.medium \
@@ -55,7 +67,7 @@ jobs:
 
           echo "Instance ID: $INSTANCE_ID"
 
-          # Wait for the instance to be running
+          # Wait for EC2-Instance to be running
           aws ec2 wait instance-running --instance-ids $INSTANCE_ID
 
           # Output the instance public DNS
@@ -64,3 +76,51 @@ jobs:
             --query 'Reservations[0].Instances[0].PublicDnsName' \
             --output text)
           echo "Instance Public DNS: $INSTANCE_PUBLIC_DNS"
+          echo "INSTANCE_PUBLIC_DNS=$INSTANCE_PUBLIC_DNS" >> $GITHUB_ENV
+
+          # Output the instance public IPv4
+          INSTANCE_PUBLIC_IPV4=$(aws ec2 describe-instances \
+            --instance-ids $INSTANCE_ID \
+            --query 'Reservations[0].Instances[0].PublicIpAddress' \
+            --output text)
+          echo "Instance Public IPv4: $INSTANCE_PUBLIC_IPV4"
+          echo "INSTANCE_PUBLIC_IPV4=$INSTANCE_PUBLIC_IPV4" >> $GITHUB_ENV
+          sleep 5
+
+      # Step 6: Connect to EC2 Instance and Deploy API & CLIENT
+      - name: Connect server and pull image Frontend/Backend
+        env:
+          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
+          INSTANCE_PUBLIC_IPV4: ${{ env.INSTANCE_PUBLIC_IPV4 }}
+          INSTANCE_PUBLIC_DNS: ${{ env.INSTANCE_PUBLIC_DNS }}
+          REPOSITORYAPI: ${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-api
+          REPOSITORYCLIENT: ${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-client
+        run: |
+          echo "$PRIVATE_KEY" > private_key 
+          chmod 600 private_key
+          echo "SSH User: ${{secrets.SSH_USER }}"
+          echo "EC2 Instance DNS: ${{ env.INSTANCE_PUBLIC_DNS }}"
+          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ env.INSTANCE_PUBLIC_DNS }} << EOF
+          sudo yum install -y docker
+          sudo systemctl start docker
+
+          echo "Deploying API"
+          sudo docker pull $REPOSITORYAPI:latest
+          sudo docker run -d --name foodadvisor-api \
+            -p 1337:1337 \
+            -e HOST=0.0.0.0 \
+            -e PORT=1337 \
+            -e STRAPI_ADMIN_CLIENT_URL=http://${INSTANCE_PUBLIC_IPV4}:3000 \
+            -e STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=${{ secrets.JWT_SECRET }} \
+            $REPOSITORYAPI:latest
+
+          echo "Deploying Client"
+          sudo docker pull $REPOSITORYCLIENT:latest
+          sudo docker run -d --name foodadvisor-client \
+            -p 3000:3000 \
+            -e NEXT_PUBLIC_API_URL=http://${INSTANCE_PUBLIC_IPV4}:1337 \
+            $REPOSITORYCLIENT:latest  
+
+          echo "Deployed API: http://${INSTANCE_PUBLIC_IPV4}:1337/"
+          echo "Deployed Client: http://${INSTANCE_PUBLIC_IPV4}:3000/"
+          EOF
